version: '3'

services:
  bark-benchmark:
    image: saladtechnologies/bark-benchmark:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      # We want this to run forever
      BENCHMARK_SIZE: -1

      # This is used to identify the benchmark,
      # and we can query by it in DynamoDB
      BENCHMARK_ID: bark-benchmark-test

      # This is the name of the queue that the benchmark
      # will poll for work, via the QUEUE_URL
      QUEUE_NAME: ${QUEUE_NAME:-recipes-to-read}

      # You will need to set these values in the environment
      # before running `docker compose up`
      REPORTING_URL: ${REPORTING_URL:-https://localhost:3000}
      REPORTING_API_KEY: ${REPORTING_API_KEY:-1234567890}
      QUEUE_URL: ${QUEUE_URL:-https://localhost:9324}
